---
- id: harper-cli
  name: harper-cli
  description: This hook runs the harper-cli grammar checker against files
  entry: harper/harper-cli Lint
  language: rust
  pass_filenames: True
  types: [text]
